"""empty message

Revision ID: 51237db1fe92
Revises: ba8f24044225
Create Date: 2018-08-30 14:35:07.734188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51237db1fe92'
down_revision = 'ba8f24044225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', '_ulikes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('_ulikes', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
