"""empty message

Revision ID: 5b4c2cbefecb
Revises: 7c45afdfbb0d
Create Date: 2018-08-21 04:43:39.485238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4c2cbefecb'
down_revision = '7c45afdfbb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('user', sa.Column('code', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('confirmed', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['code'])
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'confirmed')
    op.drop_column('user', 'code')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
