"""empty message

Revision ID: 87ac7daa2d12
Revises: f1088395dd0b
Create Date: 2018-08-30 15:20:38.136145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ac7daa2d12'
down_revision = 'f1088395dd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('like', 'user_id')
    # ### end Alembic commands ###
