"""empty message

Revision ID: d9146c618759
Revises: e68012009a35
Create Date: 2018-10-10 18:00:17.497374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9146c618759'
down_revision = 'e68012009a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_image_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_image_key', 'user', ['image'])
    # ### end Alembic commands ###
