"""empty message

Revision ID: e68012009a35
Revises: 0e520ceed1b5
Create Date: 2018-09-04 06:54:22.879066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68012009a35'
down_revision = '0e520ceed1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_phone_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_phone_key', 'user', ['phone'])
    # ### end Alembic commands ###
