"""empty message

Revision ID: f1088395dd0b
Revises: 51237db1fe92
Create Date: 2018-08-30 15:08:43.769347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1088395dd0b'
down_revision = '51237db1fe92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('like_user_id_fkey', 'like', type_='foreignkey')
    op.drop_column('like', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('like_user_id_fkey', 'like', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
